input("< New Player signing on. Press Enter to continue. > ")
print("")
from pyfiglet import Figlet

fig = Figlet(font='graffiti')
banner = fig.renderText("Asunder : Fall of Powers")

print(banner)
print("")
print("Hello player! I hope you're ready to start your adventure.")

def title():
    answer = input("To enter Story Mode, type 'New Game. ")
    if answer == "New Game":
        print("< Entering Story Mode >")
    else:
        print("< Error: Wrong Command. Try again. >")
        title()

def intro():
    print("")
    print("Long ago, there was a legend... that if you went down to the old well at midnight on a full moon \n     bringing your most prized possesion, you could unlock a portal to a new world")
    print("")
    print("Rumored that you could start a new life, in a new world, with magical abilities...")
    print("")
    input("Press Okay or Enter to continue. ")
    print("")

    print("You wake up to someone calling you. ")
    input("???: Hello? Oh you must be the last new villager! Welcome to Asunder. ")
    input("???: My name is Layla. I'm the guide for the new spirits.")
    name = input("Layla: What's your name young one? ")
    input("You: My name is " + name + ".")
    input("Layla: Nice to meet you " + name + ". Let's take you to meet the others!")
    print("You and Layla walk towards an old tower.")
    print("")
    input("You: What do you mean others?")
    input("Layla: There are many people, such as yourself, whose spirits have been brought here.")
    input("Layla: We were waiting for you so I can help you all find out your powers together.")
    input("Layla: You see here in Asunder, if your spirit has traveled here, then you will be granted magical abilities.")
    input("Layla: and it's my job to help you find them!")

    print("")
    print("You and Layla enter the old tower and you notice about five other people who look to be around your age.")
    print("")

    print("You sit next to a blonde boy who seems to be holding a flame in his hands.")
    print("???: Hey, I'm Asher! What's your name?")
    response = input("Do you A) Say nothing or B) Say your name?")
    if response == 'A':
        print("Asher: Ohhh I see you're just shy.")
        input("Asher: Don't worry, I'll be your other guide down here.")
        input("Asher: It may not be my job but I'll sure try.")
    else:
        print("Asher: Nice to meet you " + name + "! You seem pretty cool, I think we could be great friends.")

    print("")
    input("Layla: Okay everyone, it's very important to understand that you must not take advantage of your powers.")
    print("Layla: Doing so could result in your spirit being sent to Nankan.")
    input("< The whole room fell silent. >")
    letter = input("Do you A) Ask about Nankan or B) Say nothing.")
    if letter == 'B':
        print("???: What in the heck is Nankan?")
    else:
        print("You: Umm.. what is Nankan actually?")


    input("Layla: Nankan is the home of our enemies, we have been fighting with them for centuries.")
    input("Layla: They've caused great damage and pain to our great home, Asunder.")
    input("Layla: When spirits take advantage of their powers and don't use them properly, they get sent to Nankan.")
    input("Layla: A place full of greed and envy.")
    input("Asher: So wait does that mean--")
    input("Layla: No more questions, it's getting pretty late and you all need to rest to charge your powers.")
    print("< You end up bunking with Asher and try to sleep >")
    print("")


def firstnight():
    print("< A little while later, you wake up to a noise from down the hall. >")
    night = input("Do you A) Go back to sleep, or B) Find out what the noise was?")
    if night == 'A':
        print("< You try to forget about the noise and go back to sleep. > ")
    else:
        print("< You walk out of your room to find Asher in the hallway, he seems to be holding a bag. >")
        print("")
        input("You: Asher? What are you doing?")
        print("< You scared Asher causing him to almost drop his bag. >")
        name = input("Asher: Oops! Oh hey, um sorry what was your name again?")
        input("You: It's " + name + ".")
        input("Asher: Right, right, " + name + ". My bad.")
        input("Asher: I was just grabbing a snack, late night munchies.")
        print("< Asher holds up a bag of potato chips and laughs. >")
        input("You: ...Um okay. Mind if I have some?")
        input("Asher: Huh? Oh sure! Take some.")
        print("< You share a bag of chips with Asher. >")
        input("Asher: So what do you think of Asunder so far?")
        chips = input(" A) This place is weird, or B) It seems pretty cool.")
        if chips == 'A':
            print("Asher: Yea it's definitely a bit weird at first, but it's not as bad as it seems.")
        else:
            print("Asher: Really? Most people find it strange at first. But you're right it's pretty cool here.")
        print("")
        input("< You stay up late talking with Asher about Asunder. >")
        print("")
        print("")


def meetingNaomi():
    print("< After a long first night, you here a loud crash in the main room. >")
    print("")
    input("< You and Asher walk out and find one of the walls with a hole in it. \n   Along with Layla and some other girl who is dressed in battle armour. >")
    input("Layla: What have I told you about letting your anger getting the best of you?")
    input("???: I can't help it Layla! \n The Nankan army isn't even playing fair at this point, and we have no way of knowing their plans.")
    input("Layla: Trust me, I know. But that doesn't mean you can come in and PUNCH MY WALL!")
    input("???: I'll pay for the damage later, \n but we've been on the same line for weeks and their army is getting stronger and stronger.")
    input("???: It won't be long until they break the guard walls.")
    input("Layla: I've heard, but please don't come running into my house like that.")
    input("Layla: Especially when I have new spirits that--")
    print("< Layla and the other girl notice you and Asher standing in the hall. >")
    print("")
    input("???: Asher? What are you doing here? You should be helping out with the army.")
    input("Asher: Oh um hey Naomi! I am actually, I came here to find out which one of the new spirts could help out.")
    input("Asher: And I think I've found them!")
    print("< Asher points at you. >")
    print("")
    input("You: Wait what? I don't even have my powers.")
    input("Asher: Sure you do, it seems like your power charm appeared while you were sleeping.")
    print("")
    print("< You look down and see a necklace glowing a bright blue and white. >")
    input("Naomi: Wow kid, you're pretty powerful.")
    input("Asher: What? No fair you've got tier V Ice powers and invisibility?! Luckyyyy.")
    input("Layla: What these two mean is yes, you are powerful. \n Tier V Ice Powers is the second highest ice powers you can have. \n And then invisibility is a pretty rare power too.")
    input("Layla: Naomi and Asher, can you take them to the training grounds since they've already gained their powers?")
    print("Naomi: Sure Layla, let's go kid.")
    name = input("Hey I have a name actually. It's ")
    input("Naomi: Yea whatever let's get going.")
    input("Asher: Don't worry " + name + ". Naomi is a little intimidating at first but she's got a nice side somewhere.")
    input("Naomi: ASHER! You do realize I can hear you right?")
    input("Asher: Ha... I didn't say anything I swear.")
    print("")


def training():
    print("< All three of you walk into town into what seems to be an obstacle course. >")
    input("Naomi: Alright kid, let's see what you got.")
    input("Asher: To activate your powers, just try and focus on the energy coming from your charm.")
    power = input("What were the colors of your charm? \n A) Bright Blue and White B) Bright Red and Orange. ")
    if power == "A":
        print("< You feel a cold energy charge through you. \n You then realize your hands contain a blue flame with ice pieces. >")
        input("Naomi: Not bad kid, not bad.")
        input("Naomi: Try shooting those targets.")
        shoot = input("< You raise your arms up and shoot A) The Targets or B) The Barrels. ")
        if shoot == "A":
            print("Asher: Hey you did it!")
            input("Naomi: Let's take you to your first mini boss.")
        else:
            print("Naomi: Um kid... that's the wrong target. Try again.")
            training()
    else:
        print("< Nothing seems to happen. Try again. >")
        training()


def trainTwo():
    name = input("TYPE NAME FOR SAVE FILE ")
    print("")
    print("< You walk into a cave with Naomi and Asher >")
    input("Asher: Okay " + name +", in this cave, there are these little creaters called Nan Goblins.")
    input("Naomi: The little things are annoying and a bit challenging but they are the easiest to start with.")
    input("Asher: We'll be watching from that ledge, so if you need help don't worry we're not far")
    print("")
    print("< You walk deeper into the cave and here a noise not far up ahead. >")
    input("< Walking towards the noise, you see two Nan Goblins sitting on the floor of the cave. >")
    shot = input("Do you A) Shoot at cave ceiling or B) Shoot at the Goblin? ")
    if shot == 'A':
        input("< You shoot the ceiling causing rock to fall onto both of the goblins. >")
        print("Asher: Way to go " + name + "! Some others will be coming so stay alert.")
    else:
        print("< You shoot at the Goblin and only manage to kill one of them. >")
        print("")
        input(" < You get injured. Try again. >")
        trainTwo()
    print("")
    input("< Shortly after Asher stops talking, you here what seems to be four more gobling coming towards you. >")
    power = input("Do you A) Turn invisible or B) Shoot an ice beam? ")
    if power == 'A':
        print("< You turn invisible causing the goblins to run right past you. >")
    else:
        print("< You shoot an ice bean towards the goblins and manage to hit two of them. >")
        input("< The other two managed to dodge the attack and attack you. >")
        print("")
        input("< You get injured. Try again. >")
        trainTwo()
    print("")
    print("Naomi: Hmm. Not bad " + name + ", considering this is your first try.")
    input("Naomi: Normally first timers aren't as good at controlling, or even using their powers.")
    input("Asher: I know that look on your face Naomi...")
    input("Asher: Do you really think their ready?")
    input("Naomi: Have you ever seen anyone gain control of their powers that quickly? Especially with powers like theirs.")
    input("You: What are you guys talking about? Am I ready for what?")
    print("")
    input("< Asher and Naomi go silent for a minute. >")
    print("")
    input("Naomi: " + name + "... I think you're ready to fight for Asunder.")
    print("")
    print("< You freeze, and there's a pause >")
    response = input("How do you react? A) Freak Out or B) Be Excited. ")
    if response == "A":
        print("")
        print("You: You're joking right?")
        input("Asher: Naomi doesn't joke much with this kind of stuff.")
        input("You: You're both CRAZY!")
        input("You: I can't fight in a battle, I just got here!")
        input("You: Not to mention my training with my powers.")
        input("You: Oh my gosh. MY POWERS!. I don't even--")
        input("Naomi: Relax kid, Asher and I will be with you the whole time.")
        input("Asher: We won't let anything happen to you.")
        input("Asher: And trust me on that. Along with tier IV fire powers, I also have tier III healing powers.")
        input("Naomi: Combined with my super strength and tier IV wind bending powers, we'll all be unstoppable together.")
        input("You: O-okay, if you guys are really sure about this... I'll do it.")
    else:
        print("")
        print("You: I can't believe this.")
        input("Asher: Are you okay " + name + "? I know this is a lot.")
        input("You: Okay? I'm better than okay.")
        input("You: I get to fight in a REAL BATTLE.")
        input("Naomi: Love the energy kid. Not many people react like that when they hear they have to go to battle.")
        input("You: Why wouldn't I be excited? This is literally the best thing ever. Besides my powers.")
        input("Naomi: Well Asher here was a complete baby when he heard he was sent to fight.")
        input("Asher: HEY! I wasn't a complete baby. I didn't react that bad.")
        input("Naomi: You stayed up all night basically shaking. Not to mention you also--")
        input("Asher: OKAY! We should probably get this one ready for battle.")
        input("You: Wait. Where will you two be? I'm no fighting on my own am I?")
        input("Naomi: Relax kid, Asher and I will be with you the whole time.")
        input("Asher: And we won't let anything happen to you, trust me on that.")
        input("Asher: Along with tier IV fire powers, I also have tier III healing powers.")
        input("Naomi: Combined with my super strength and tier IV wind bending powers, we'll all be unstoppable together.")
    print("")
    input("Asher: Soooo... does this mean best friends?")
    input("You: Wait really?!")
    print("")
    print("< You and Asher look towards Naomi. >")
    print("")
    input("Naomi: ...")
    input("Naomi: Yea, " + name + ". Best friends")


def battlingstory():
    name = input("TYPE NAME FOR SAVE FILE ")
    print("")
    print("")
    print("Once you started fighting alongside Asher and Naomi. You began to start a new, never ending friendship.")
    input("For years, the three of you fought for Asunder, bringing them closer and closer to victory.")
    print("")
    input("The Nankan army didn't stand a chance with the three of you working against them.")
    input("They called you three...")
    from pyfiglet import Figlet

    fig = Figlet(font='graffiti')
    banner = fig.renderText("The Alpha Powers")

    print(banner)
    print("")
    input("However, the Nankan kingdom knew they'd have to get rid of these 'Alpha Powers'.")
    input("Their king had called his most powerful fighter.")
    print("")
    input("His own son Tristan. Also known as The Assailant. \n He's brought disaster to any enemy of the Nankan, never losing a battle, and can wipe out an entire army.")
    input("Your friends Naomi and Asher managed to somehow lock him away in a far away place where not even the king would find him. \n It was a long, horrible battle, your two freinds barely survived.")
    input("But now Tristan is back, and he's planning to attack at full force.")
    print("")
    print("")
    input("I hope you're ready for battle " + name + ". Because this will determine the fate of you and your friends.")


def finaleone():
    name = input("TYPE NAME FOR SAVE FILE ")
    print("")
    print("")
    input("< You, Naomi, and Asher are walking towards the rest of the army prepairing for the last battle against Nankan. >")
    print("")
    input("Asher: Guys! This is really the last battle against Nankan!")
    input("Asher: If we win this, we'll be heros and Nankan will be kept where they belong.")
    input("Naomi: As much as I enjoy seeing the defeated look of the Nankan army after each battle, I'll kind of miss fighting with you guys.")
    input("You: Aww Naomi, no need to get sentimental. Even if it's about.. missing fighting.")
    input("Naomi: Me? Be sentimental? Puh-lease.")
    input("Asher: Well, that's the closest you'll get to being soft.")
    input("Naomi: You're not wrong there. But who knew that little " + name + " would bring us and Asunder to where we are today.")
    input("You: Hey I can't take all the credit, if it weren't for you two sticking with me, I'd probably be some random worker.")
    input("You: Not to mention it was also your powers that helped bring us all here.")
    input("Asher: That and the day you and I woke up because Naomi punched Layla's wall.")
    print("")
    input("< Naomi casted a strong wind to blow towards Asher, causing him to trip and fall. >")
    print("")
    input("Asher: HEY! Not my fault you got angry that day.")
    input("Naomi: Ha no, but it's going to be your fault if I get angry right now.")
    input("You: Relax Naomi, you can kill him later, we have a battle to win.")
    print("")
    input("< The three of you go off to put on your battle armour. >")
    input("< Naomi calls the army and the three of you lead them to the Nankan borders.")
    print("")
    print("")
    print("The army of Asunder marches towards Nankan, stopping at the fall line. \n Across from them, stands the Nankan Army, smaller than what it used to be.")
    print("")
    input("Asher: This will be a piece of cake!")
    input("Asher: There's no way they can defeat us.")
    print("")
    print("Suddenly, the skies became a dark grey and the Nankan army parted down the middle to reveal a path.")
    print("")
    input("Asher: Wait, that isn't who I think it is right?")
    input("Naomi: No... it can't be. We locked him up years ago, right?")
    input("Asher: Yea but... how did he--?")
    input("Naomi: I bet you the Nankan King found him and helped free him.")
    input("You: Who are you guys talking about?")
    print("")
    print("< There was a long pause. >")
    print("")
    input("Asher: " + name + ", do you remember hearing the legends about the Nankan Prince?")
    input("You: Yea, but what does that have to do with that guy?")
    input("Asher: That's not just some guy. That's--")
    input("Naomi: Tristan... Prince of Nankan.")
    input("You: Wait. That's him?! But how? I thought you two got rid of him?!")
    input("Naomi: I thought so too, but he broke free somehow.")
    print("")
    print("< You see a boy with piercing grey eyes, eyes that seem to be glowing, emerge from the Nankan army")
    input("< Everyone has gone silent now >")
    print("")
    input("Tristan: Well well well... if it isn't the Asunder army.")
    input("Tristan: And of course my dear friends Naomi and Asher.")
    input("Naomi: How the hell did you get out?")
    input("Tristan: ")
    print("< Tristan looks at you and pauses. >")
    print("")


finaleone()